JenniferEinstein/9.6_capstone-team-3-frontend

package-lock.json, package.json, src/pages/AllEvents.js, src/pages/Event.js
Mapped through events and started working on CSS format with bootstrap, I am kinda rusty but I do have the information formatted similar to the example event page on the trello board. I think I can make it look more like the wireframe once I get the collapse to work and can focus on an algorithm for date.
=> Events changes so far

src/css/Navbar.css
=> latest homepage update

src/components/FullGallery.js, src/css/fullGallery.css
=> gallery page css update, cards have some styling and min height

src/components/Footer.js, src/css/footer.css, src/images/picture-urls.txt
Also replaced the word logo with the logo. The logo is currently too big and I need to and am trying to resize it. Also changed the text color to black. Also, updated links in the footer.
=> Change footer color to blue.

src/css/Events.css, src/pages/AllEvents.js, src/pages/CurrentEvent.js, src/pages/UpcomingEvents.js
1. Finished the deadline countdown 
2. Time until for upcoming events
3. Styling with Css final revisions 
4. Need opinions on hero image layout
=> Styling & Codingg

src/css/Signup.css, src/css/login.css, src/pages/Login.js, src/pages/Signup.js
added css to  signup, and updated login button container css
=> Joanavel loginpage

src/css/fullGallery.css, src/css/homepage.css
, made it smaller and centered the button
=> made more changes to the signup now container

src/App.js, src/components/MessageProof.js
For example, I had the upload set to success regardless of whether or not it was successful. 
Changes:
Rerouted the about route back to the about page. Got rid of auto succ……ess. Corrected Spelling and grammar.
=> Dummy changes made just for the presentation were reverted.

src/App.js, src/components/CurrentEvent.js, src/components/EventSignup.js, src/css/Events.css
Layout and Style Changes To EventsSignUp.js and Current Events.js
Changes alternate navigation on App.js to LoginModal component
=> Responsive Design, Events Registration REVAMP

src/components/PublicProfile.js
Designed the user profile to have a complete functioning UI/UX based on  null backend data whether they're the user signed in, or just viewing another user's profile who may have null data in backend.
=> Added more server side data to user profile with conditional UI/UX

src/App.js, src/components/Footer.js
The sign up button now disappears when a user logs in, Yay. And the links on the bottom are moved over like Joanavel suggested, but I don't know that it looks great.
=> Fixed Footer

src/components/EventSignup.js, src/css/Events.css
Responsive design is great until around 205px then from there to about 199px it gets mid but launchable on Events Page. 
Minor issues with toggle feature on EventsSignUp page when page is under 365px, the inputs stretch, I think I'll meet with John in a few days to go over some media queries. - solved.
Now the text for labels for clothes inputs are extremely tiny when under 200px.
=> Everything Events Branch Final

src/App.js, src/components/MessageProof.js, src/components/UploadModal.js, src/firebaseStorage.js, src/pages/Gallery.js
1).The issue was related to how the storage reference was created in the UploadModal.js. Firebase storage references are created using ref() function and specific paths.  
This is the route:   (gs://happiness-exchange-capstone.appspot.com/images).   
2). On the firebaseStorage.js: I had to reference the image folder:  
Created a reference to the root of your Cloud Storage bucket
const storageRef = ref(storage, 'images');  
3). On the UploadModal.js modal I updated the import  
 import { storageRef } from '../firebaseStorage'; 
 
 I also used the storage reference from firebaseStorage.js
  
const fileName = `${Date.now()}_${selectedFile.name}`;
const fileRef = ref(storageRef, fileName);   
=> firebase storage- user able to upload

src/components/Footer.js, src/components/UploadModal.js, src/css/Gallery.css, src/css/LoginModal.css, src/css/Navbar.css, src/css/Upload.css, src/css/uploadModal.css, src/pages/Gallery.js
=> Joanavel-upload modal given CSS

src/components/UploadModal.js
Creates picture post on back end, slight bug saying it fails but its not it actually works
=> Upload Modal Post to back end works

src/components/MessageMatch.js, src/components/MessageProof.js, src/components/UploadModal.js, src/css/Upload.css, src/css/messages.css
There is now alt text and the user can see a thumbnail of the image uploaded before sending. The modal now scrolls for when the user adds alt text and a thumbnail,  but I just noticed that the top is being cut off so I will go and fix that. Also, I seem to have lost the functionality.
=> Upload Picture Modal Updated

src/components/MessageMatch.js, src/pages/AdminMatching.js
It should be good to go. See commits for more information.
=> Fixed the navigation problem

src/App.css, src/components/Footer.js, src/css/footer.css
… so that the quick links are first when the screen is small and the two are on top of each other.
=> Moved footer columns around, got rid of excess space in footer, et al.

src/components/EventSignup.js, src/css/Events.css
These are to make them look less like "Mad Libs".
=> Changes to Events Registration Page

src/components/UpcomingEvents.js, src/css/Events.css
Made rotation slower, changed title of timeline for upcoming events.
=> Changes on Events Page

src/App.css, src/components/UserExchanges.js, src/css/Events.css, src/css/about.css, src/css/uploadModal.css, src/pages/About.js
=> Joanavel user exchange v2
